server:
  port: 8081
  context-path: "/"
logging:
  level:
    org:
      springframework:
        web: DEBUG
security:
  jwt:
    client-secret: XY7kmzoNzl100
    token-validity-seconds: 6060

spring:
  datasource:
        url: jdbc:mysql://localhost:3306/talk2
        username: root
        password: welcome_123!
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 10
        max-idle: 5
        min-idle: 1
        testWhileIdle: true
        test-on-borrow: true
        validationQuery: SELECT 1
        timeBetweenEvictionRunsMillis: 5000
        min-evictable-idle-time-millis: 60000
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
      
  data:
    rest:
      base-path: "/api"
